In [1]:
import numpy as np
import pandas as pd

In [4]:
from tensorflow.keras import datasets

In [5]:
(x_train, y_train), (x_test, y_test)=datasets.mnist.load_data()

In [6]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
x_train.shape #dataset contains 60k images

(60000, 28, 28)

In [9]:
x_test.shape 

(10000, 28, 28)

In [10]:
width, height=28, 28 #every image contains 3rgb channels, height, width, rgb
input_shape=(width, height, 1)

In [11]:
input_shape

(28, 28, 1)

In [12]:
x_train=x_train.reshape(x_train.shape[0], height, width, 1)
x_test=x_test.reshape(x_test.shape[0], height, width, 1)

In [13]:
x_train.shape # we use one to signify grayscale

(60000, 28, 28, 1)

In [14]:
y_train.shape

(60000,)

In [15]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val=train_test_split(x_train, y_train, test_size=0.1)

In [17]:
len(x_val)

6000

In [18]:
x_train=(x_train-x_train.mean())/x_train.std() #feature scaling
x_val=(x_val-x_val.mean())/x_val.std()
x_test=(x_test-x_test.mean())/x_test.std()

In [19]:
from tensorflow import keras

In [20]:
num_labels=10
y_train=keras.utils.to_categorical(y_train)

In [21]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [22]:
y_val=keras.utils.to_categorical(y_val)
y_test=keras.utils.to_categorical(y_test)

In [23]:
#MODEL
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D

In [24]:
#LENET 5 ARCHITECTURE HAS 5 LAYERS
model=Sequential()  #extracting these 5 layers
model.add(Conv2D(6, kernel_size=(5,5), strides=(1,1), activation='tanh', input_shape=(28, 28, 1)))
model.add(AveragePooling2D(pool_size=(2,2), strides=(1,1)))
model.add(Conv2D(16, kernel_size=(5,5), strides=(1,1), activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2), strides=(2,2)))
model.add(Conv2D(120, kernel_size=(5,5), strides=(1,1), activation='tanh'))
model.add(Flatten())
model.add(Dense(84, activation='tanh'))
model.add(Dense(num_labels, activation='softmax'))

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (Average  (None, 23, 23, 6)         0         
 Pooling2D)                                                      
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_1 (Avera  (None, 9, 9, 16)          0         
 gePooling2D)                                                    
                                                                 
 conv2d_2 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten (Flatten)           (None, 3000)              0

In [26]:
model.compile(loss=keras.losses.categorical_crossentropy, optimizer='adam', metrics=['accuracy'])
#to minimize losses using loss function

In [27]:
history=model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=1, validation_data=(x_val, y_val))

Epoch 1/5


1688/1688 [==============================] - 17s 9ms/step - loss: 0.2162 - accuracy: 0.9363 - val_loss: 0.1378 - val_accuracy: 0.9593
Epoch 2/5
1688/1688 [==============================] - 18s 11ms/step - loss: 0.0970 - accuracy: 0.9708 - val_loss: 0.1257 - val_accuracy: 0.9598
Epoch 3/5
1688/1688 [==============================] - 18s 11ms/step - loss: 0.0790 - accuracy: 0.9761 - val_loss: 0.0814 - val_accuracy: 0.9740
Epoch 4/5
1688/1688 [==============================] - 18s 11ms/step - loss: 0.0689 - accuracy: 0.9785 - val_loss: 0.0786 - val_accuracy: 0.9800
Epoch 5/5
1688/1688 [==============================] - 18s 11ms/step - loss: 0.0634 - accuracy: 0.9805 - val_loss: 0.0799 - val_accuracy: 0.9783


In [28]:
score= model.evaluate(x_test, y_test, verbose=1)

313/313 [==============================] - 1s 4ms/step - loss: 0.0671 - accuracy: 0.9795


In [29]:
score

[0.06712142378091812, 0.9794999957084656]